<?php

namespace SIEBundle\Entity;

/**
 * AsientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsientosRepository extends \Doctrine\ORM\EntityRepository
{
}
