<?php

namespace SIEBundle\Entity;

/**
 * BoletoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletoRepository extends \Doctrine\ORM\EntityRepository
{
}
