<?php

namespace SIEBundle\Entity;

/**
 * CarteleraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteleraRepository extends \Doctrine\ORM\EntityRepository
{
}
