<?php

namespace SIEBundle\Entity;

/**
 * DulceriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DulceriaRepository extends \Doctrine\ORM\EntityRepository
{
}
