<?php

namespace SIEBundle\Entity;

/**
 * EstatusPeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusPeliculaRepository extends \Doctrine\ORM\EntityRepository
{
}
