<?php

namespace SIEBundle\Entity;

/**
 * EstadoAsientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoAsientosRepository extends \Doctrine\ORM\EntityRepository
{
}
