<?php

namespace SIEBundle\Entity;

/**
 * FuncionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionRepository extends \Doctrine\ORM\EntityRepository
{
}
