<?php

namespace SIEBundle\Entity;

/**
 * TaquillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaquillaRepository extends \Doctrine\ORM\EntityRepository
{
}
