<?php

namespace SIEBundle\Entity;

/**
 * VentaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
