login:
    path:    /login
    defaults: { _controller: SIEBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:    /logout

sie_homepage:
    path:     /
    defaults: { _controller: SIEBundle:Default:index }
#Catalogos
roles:
    path:    /roles
    defaults: { _controller:SIEBundle:Role:all }
roles_new:
    path:    /roles/nuevo
    defaults: { _controller: SIEBundle:Role:nuevo  }
rol_edit:
    path:    /roles/{id}/editar
    defaults: { _controller: SIEBundle:Role:edit }
rol_delete:
    path:    /rol/{id}/eliminar
    defaults: { _controller: SIEBundle:Role:delete }
puesto_nuevo:
    path:    /puesto/nuevo
    defaults: { _controller: SIEBundle:Puesto:nuevo }
puesto_edit:
    path:    /puesto/{id}/editar
    defaults: { _controller: SIEBundle:Puesto:editar }
puesto_delete:
    path:    /puesto/{id}/eliminar
    defaults: { _controller: SIEBundle:Puesto:eliminar }
puestos:
    path:    /puestos
    defaults: { _controller: SIEBundle:Puesto:puestos }
categoria_new:
    path:    /categoria/nuevo
    defaults: { _controller: SIEBundle:Categoria:nuevo }
categorias:
    path:    /categorias
    defaults: { _controller: SIEBundle:Categoria:categorias }
categoria_edit:
    path:    /categoria/{id}/editar
    defaults: { _controller: SIEBundle:Categoria:editar }
categoria_delete:
    path:    /categoria/{id}/eliminar
    defaults: { _controller: SIEBundle:Categoria:eliminar }
boletos_new:
    path:    /boletos/nuevo
    defaults: { _controller: SIEBundle:Boletos:nuevo }
boletos:
    path:    /boletos
    defaults: { _controller: SIEBundle:Boletos:boletos }
boletos_edit:
    path:    /boletos/{id}/editar
    defaults: { _controller: SIEBundle:Boletos:editar }
boletos_delete:
    path:    /boletos/{id}/eliminar
    defaults: { _controller: SIEBundle:Boletos:eliminar }
sala_new:
    path:    /sala/nueva
    defaults: { _controller: SIEBundle:Sala:nuevo }
salas:
    path:    /salas
    defaults: { _controller: SIEBundle:Sala:salas }
sala_edit:
    path:    /sala/{id}/editar
    defaults: { _controller: SIEBundle:Sala:editar }
sala_delete:
    path:    /sala/{id}/eliminar
    defaults: { _controller: SIEBundle:Sala:eliminar }
edo_aciento_new:
    path:   /edo_aciento/nuevo
    defaults: { _controller: SIEBundle:EdoAciento:nuevo }
edo_aciento:
    path:    /edo_aciento
    defaults: { _controller: SIEBundle:EdoAciento:asientos }
edo_aciento_delete:
    path:    /edo_aciento/{id}/eliminar
    defaults: { _controller: SIEBundle:EdoAciento:eliminar }
edo_aciento_edit:
    path:   /edo_aciento/{id}/edit
    defaults: { _controller: SIEBundle:EdoAciento:editar }
#Usuarios
user_new:
    path:    /user/{id}/nuevo
    defaults: { _controller: SIEBundle:User:nuevo }
users:
    path:    /users
    defaults: { _controller: SIEBundle:User:users }
user_detalle:
    path:    /user/{id}/detalle
    defaults: { _controller:SIEBundle:User:user }
user_edit:
    path:     /user/{id}/update
    defaults: { _controller: SIEBundle:User:update }
empleados_new:
    path:    /empleado/nuevo
    defaults: { _controller: SIEBundle:Empleado:nuevo }
#proveedores
proveedores:
    path:    /proveedores
    defaults: { _controller: SIEBundle:Proveedores:proveedores }
proveedores_detalle:
    path:    /proveedores/detalle
    defaults: { _controller: SIEBundle:Proveedores:detalle }
proveedores_nuevo:
    path:    /proveedores/nuevo
    defaults: { _controller: SIEBundle:Proveedores:nuevo }
#Peliculas
peliculas_new:
    path:    /peliculas/nuevo
    defaults: { _controller: SIEBundle:Peliculas:nuevo }
peluculas:
    path:    /peliculas
    defaults: { _controller: SIEBundle:Peliculas:peliculas}